### ISSUE TITLE
not receiving any packets

### ISSUE THREAD

**Issue by heaversm** [kylemcdonald/ofxFaceShift#1]
Hi - I've got face shift running in streaming mode using the default communication settings (host 127.0.0.1), port 33433, and ofxFaceShift open and listening on 33433 (sending to 8338) and it's not receiving any packets. Any idea on how to troubleshoot this?

**Comment by kylemcdonald** [comment]
Ah I jus realized, can you make sure faceshift is set up to stream over UDP instead of TCP? It's in the preferences. I forget what the default setting is.

**Comment by dackdel** [comment]
was just about to suggest the same. I just changed it to UDP but even then I had to run the program twice before receiving packets. "example-visualize" does not seem to get the data tho. am I doing something wrong?

**Comment by kylemcdonald** [comment]
Make sure you're not running both apps at the same time, only one program can be bound to a single port at any moment.

**Comment by heaversm** [comment]
Yeah - I had tried UDP, but I think that I just needed to sort of restart everything. Thanks!

**Comment by walker407** [comment]
example-visualize works after restarting everything like heaversm described, but example-blendshapes still doesn't work for me.

**Comment by walker407** [comment]
Nevermind, I forgot you had to export the profile from Face Shift to the export folder. Thank you for the addon!
