### ISSUE TITLE
issue message

### ISSUE THREAD

**Issue by dackdel** [kylemcdonald/ofxFaceShift#2]
the example-visualise is throwing up an issue message  " __throw_out_of_range(__N("vector::_M_range_check"));" this line to be exact.

**Comment by kylemcdonald** [comment]
Aha that was probably me forgetting to add the blendshape list for data. Just copy data/ from a working example and I'll fix this. Thanks!

**Comment by dackdel** [comment]
Cheers.

**Comment by dackdel** [comment]
.
