### ISSUE TITLE
turning off and on faceshift display

### ISSUE THREAD

**Issue by heaversm** [kylemcdonald/ofxFaceShift#4]
Hi - I'm trying to do an oF project for a visual performance where there are 3 scenes, in the first, I play a video, in the second I display faceshift, and in the 3rd, I play another video. I can play the first video just fine, and I can switch then to faceShift just fine, but the problem is that when I then switch to the third scene, to play another video - I just get a black screen. I suspect that I need to "shut down" the display of faceshift in some way, but I don't know how. I saw that it is using easycam, but I didn't see any method of destroying that object other than camera.end(), which I'm using. Here's my (pseudo)code:

```
void ofApp::draw(){    
    playZone();
}

void ofApp::playZone(){
    switch (curZone){
        case 0: //video
            drawVid();
            break;
        case 1: //faceshift
            drawFace();
            break;
        case 2: //video
            drawVid();
            break;
    }
}

void ofApp::drawFace(){ //your code
    cam.begin();
    glEnable(GL_DEPTH_TEST);
    ofRotateX(180);
    ofTranslate(faceShift.getPosition());
    ofScale(-1, 1, 1); // for some reason the rotation matrix x is flipped
    glMultMatrixf((GLfloat*) faceShift.getRotationMatrix().getPtr());
    ofScale(-2, 2, 2); // then we flip it back //MH - Double Size

    ofEnableLighting();
    ofSetColor(255);
    faceShift.getBlendMesh().draw();

    ofDisableLighting();
    ofSetColor(0);
    //faceShift.getBlendMesh().drawWireframe(); //MH - Don't need wireframe?

    cam.end();

}



```

**Comment by kylemcdonald** [comment]
usually black video is due to leaving lighting enabled (ofVideoPlayer has no normal, therefore it does not respond to lighting).

try adding `ofDisableLighting();` to the top of your `playZone()` and only enable it in `drawFace()` as necessary. i can imagine some side-effects leaking through somewhere/somehow...

**Comment by heaversm** [comment]
Worked perfectly, thanks!

On Sun, Sep 23, 2012 at 3:41 AM, Kyle McDonald notifications@github.comwrote:

> usually black video is due to leaving lighting enabled (ofVideoPlayer has
> no normal, therefore it does not respond to lighting).
> 
> try adding ofDisableLighting(); to the top of your playZone() and only
> enable it in drawFace() as necessary. i can imagine some side-effects
> leaking through somewhere/somehow...
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/kylemcdonald/ofxFaceShift/issues/4#issuecomment-8796163.

## 

Mike Heavers
mikeheavers.com
917-345-6634
